/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Service.DonHangSanPhamHoanChinhService;
import Service.HoaDonService;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DonHangSanPhamHoanChinh;
import model.HoaDon;

/**
 *
 * @author TB
 */
public class QuanLyHoaDon extends javax.swing.JFrame {

    List<HoaDon> lhd = new ArrayList<>();
    List<DonHangSanPhamHoanChinh> ldhsphc = new ArrayList<>();
    DonHangSanPhamHoanChinhService dhsphcsv = new DonHangSanPhamHoanChinhService();
    HoaDonService hds = new HoaDonService();
    DefaultTableModel HoaDonModel = new DefaultTableModel();
    DefaultTableModel DonHangModel = new DefaultTableModel();
    int indexHoaDon;
    int currentDefaut = 1;
    int rowsDefault = 5;
    private int currentPage = 1;
    private int rowsPerPage = 5;
    int page;
    boolean filltablenormal = true, timkiem = false;

    /**
     * Creates new form QuanLyHoaDon
     */
    public QuanLyHoaDon() {
        initComponents();
        HoaDonModel = (DefaultTableModel) tblHoaDonQL.getModel();
        DonHangModel = (DefaultTableModel) tblDonHang.getModel();
        tblHoaDonQL.setRowHeight(30);
        tblDonHang.setRowHeight(30);
        int startRow = (currentPage - 1) * rowsPerPage;
        lhd = hds.dataHoaDonPhanTrang(startRow, rowsPerPage);
        fillToTable();
        computedPagination();
        lblPage.setText(currentPage + "/" + page + "");
        cboPhuongThucThanhToan.addItem("");
        cboPhuongThucThanhToan.setSelectedIndex(3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDonQL = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNguoiTao = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cboPhuongThucThanhToan = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jdNgayBatDau = new com.toedter.calendar.JDateChooser();
        jdNgayKetThuc = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        btnTimKiemTheoNgay = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnLamMoi = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jpPhanTrang = new javax.swing.JPanel();
        btnPrev = new javax.swing.JButton();
        lblPage = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDonHang = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Hóa Đơn"));

        tblHoaDonQL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Hóa Đơn", "Phương Thức Thanh Toán", "Người Tạo", "Tổng Tiền", "Tên Khách Hàng", "Trạng Thái", "Ngày Tạo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHoaDonQL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonQLMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoaDonQL);
        if (tblHoaDonQL.getColumnModel().getColumnCount() > 0) {
            tblHoaDonQL.getColumnModel().getColumn(0).setResizable(false);
            tblHoaDonQL.getColumnModel().getColumn(1).setResizable(false);
            tblHoaDonQL.getColumnModel().getColumn(2).setResizable(false);
            tblHoaDonQL.getColumnModel().getColumn(3).setResizable(false);
            tblHoaDonQL.getColumnModel().getColumn(4).setResizable(false);
            tblHoaDonQL.getColumnModel().getColumn(5).setResizable(false);
            tblHoaDonQL.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Người Tạo");

        txtNguoiTao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNguoiTaoMouseClicked(evt);
            }
        });
        txtNguoiTao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNguoiTaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 189, Short.MAX_VALUE))
                    .addComponent(txtNguoiTao, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtNguoiTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Phương Thức Thanh Toán");

        cboPhuongThucThanhToan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiền Mặt", "Chuyển Khoản", "Quẹt Thẻ" }));
        cboPhuongThucThanhToan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboPhuongThucThanhToanMouseClicked(evt);
            }
        });
        cboPhuongThucThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPhuongThucThanhToanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 71, Short.MAX_VALUE))
                    .addComponent(cboPhuongThucThanhToan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(cboPhuongThucThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jdNgayBatDau.setDateFormatString("yyyy/MM/dd HH:mm:ss");
        jdNgayBatDau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jdNgayBatDauMouseClicked(evt);
            }
        });

        jdNgayKetThuc.setDateFormatString("yyyy/MM/dd HH:mm:ss");
        jdNgayKetThuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jdNgayKetThucMouseClicked(evt);
            }
        });

        jLabel3.setText("Tìm Kiếm Theo Ngày");

        btnTimKiemTheoNgay.setText("Tìm Kiếm");
        btnTimKiemTheoNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemTheoNgayActionPerformed(evt);
            }
        });

        jLabel4.setText("Ngày Bắt Đầu");

        jLabel5.setText("Ngày kết thúc");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jdNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jdNgayKetThuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTimKiemTheoNgay))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(66, 66, 66)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnTimKiemTheoNgay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnPrev.setText("<");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        lblPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnNext.setText(">");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPhanTrangLayout = new javax.swing.GroupLayout(jpPhanTrang);
        jpPhanTrang.setLayout(jpPhanTrangLayout);
        jpPhanTrangLayout.setHorizontalGroup(
            jpPhanTrangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPhanTrangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(lblPage, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpPhanTrangLayout.setVerticalGroup(
            jpPhanTrangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPhanTrangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpPhanTrangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPrev)
                    .addComponent(lblPage, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPhanTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPhanTrang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Đơn Hàng"));

        tblDonHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã SP", "Tên Sản Phẩm", "Màu Sắc", "Chất Liệu", "Kích thước", "Số lượng", "Đơn giá", "Thành Tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDonHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDonHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblDonHangMouseEntered(evt);
            }
        });
        tblDonHang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblDonHangKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(tblDonHang);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblDonHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDonHangMouseClicked

        //        System.out.println(soluongBanDau);
    }//GEN-LAST:event_tblDonHangMouseClicked

    private void tblDonHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDonHangMouseEntered

    }//GEN-LAST:event_tblDonHangMouseEntered

    private void tblDonHangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblDonHangKeyPressed
        //       int indexDonHang = tblGioHang.getSelectedRow();
        //        DonHang donhangchoose = ldh.get(indexDonHang);

    }//GEN-LAST:event_tblDonHangKeyPressed

    private void tblHoaDonQLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonQLMouseClicked
        int hoadonid = (int) tblHoaDonQL.getValueAt(tblHoaDonQL.getSelectedRow(), 0);
        ldhsphc = dhsphcsv.getDataHoaDonFollowId(hoadonid);
        fillToTableDonHang();
    }//GEN-LAST:event_tblHoaDonQLMouseClicked

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        jpPhanTrang.setVisible(true);
        currentPage = 1;
        rowsPerPage = 5;
        filltablenormal = true;
        timkiem = false;
        lblPage.setText(currentPage + "/" + page + "");
        int startRow = (currentPage - 1) * rowsPerPage;
        lhd = hds.dataHoaDonPhanTrang(startRow, rowsPerPage);
        if (currentPage != page) {
            btnNext.setVisible(true);
        }
        fillToTable();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void cboPhuongThucThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPhuongThucThanhToanActionPerformed
        String pttt = (String) cboPhuongThucThanhToan.getSelectedItem();
        if (pttt.equalsIgnoreCase("Tiền Mặt")) {
            lhd = hds.showDataHoaDonQLHoaDonFollowPTTT("PhuongThuc1");
            jpPhanTrang.setVisible(false);
            fillToTable();
        }
        if (pttt.equalsIgnoreCase("Chuyển khoản")) {
            lhd = hds.showDataHoaDonQLHoaDonFollowPTTT("PhuongThuc2");
            jpPhanTrang.setVisible(false);
            fillToTable();
        }
        if (pttt.equalsIgnoreCase("quẹt thẻ")) {
            lhd = hds.showDataHoaDonQLHoaDonFollowPTTT("PhuongThuc3");
            jpPhanTrang.setVisible(false);
            fillToTable();
        }
        if (pttt.equals("")) {
            jpPhanTrang.setVisible(true);
            currentPage = 1;
            rowsPerPage = 5;
            filltablenormal = true;
            timkiem = false;
            lblPage.setText(currentPage + "/" + page + "");
            int startRow = (currentPage - 1) * rowsPerPage;
            lhd = hds.dataHoaDonPhanTrang(startRow, rowsPerPage);
            if (currentPage != page) {
                btnNext.setVisible(true);
            }
            fillToTable();
        }
    }//GEN-LAST:event_cboPhuongThucThanhToanActionPerformed

    private void cboPhuongThucThanhToanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboPhuongThucThanhToanMouseClicked
        txtNguoiTao.setText("");
        jpPhanTrang.setVisible(true);
        currentPage = 1;
        rowsPerPage = 5;
        filltablenormal = true;
        timkiem = false;
        lblPage.setText(currentPage + "/" + page + "");
        int startRow = (currentPage - 1) * rowsPerPage;
        lhd = hds.dataHoaDonPhanTrang(startRow, rowsPerPage);
        if (currentPage != page) {
            btnNext.setVisible(true);
        }
        fillToTable();
        jdNgayBatDau.setDate(null);
        jdNgayKetThuc.setDate(null);
    }//GEN-LAST:event_cboPhuongThucThanhToanMouseClicked

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if (filltablenormal) {
            currentPage++;
            HoaDonModel.setRowCount(0);
            int startRow = (currentPage - 1) * rowsPerPage;
            lhd = hds.dataHoaDonPhanTrang(startRow, rowsPerPage);
            fillToTable();
            lblPage.setText(currentPage + "/" + page + "");
            if (currentPage == page) {
                btnNext.setVisible(false);
            } else {
                btnNext.setVisible(true);
            }
        }
        if (timkiem) {
            currentPage++;
            HoaDonModel.setRowCount(0);
            int startRow = (currentPage - 1) * rowsPerPage;
            DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
            String timeBatDau = dateFormat.format(jdNgayBatDau.getDate());
            String timeKetThuc = dateFormat.format(jdNgayKetThuc.getDate());
            lhd = hds.showDataHoaDonQLHoaDonFollowDateTime(timeBatDau, timeKetThuc, startRow, rowsPerPage);
            fillToTable();
            lblPage.setText("");
        }

    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        if (filltablenormal) {
            if (currentPage > 1) {
                currentPage--;
                int startRow = (currentPage - 1) * rowsPerPage;
                lhd = hds.dataHoaDonPhanTrang(startRow, rowsPerPage);
                fillToTable();
                lblPage.setText(currentPage + "/" + page + "");
                if (currentPage != page) {
                    btnNext.setVisible(true);
                }
            }
        }
        if (timkiem) {
            if (currentPage > 1) {
                currentPage--;
                int startRow = (currentPage - 1) * rowsPerPage;
                DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
                String timeBatDau = dateFormat.format(jdNgayBatDau.getDate());
                String timeKetThuc = dateFormat.format(jdNgayKetThuc.getDate());
                lhd = hds.showDataHoaDonQLHoaDonFollowDateTime(timeBatDau, timeKetThuc, startRow, rowsPerPage);
                fillToTable();
                lblPage.setText("");
                if (currentPage != page) {
                    btnNext.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnTimKiemTheoNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemTheoNgayActionPerformed
        if (jdNgayBatDau.getDate() == null || jdNgayKetThuc.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Không được bỏ trống các trường thời gian");
            return;
        }

        currentPage = 1;
        lblPage.setText("");
        rowsPerPage = 5;
        filltablenormal = false;
        timkiem = true;
        int startRow = (currentPage - 1) * rowsPerPage;

        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        String timeBatDau = dateFormat.format(jdNgayBatDau.getDate());
        String timeKetThuc = dateFormat.format(jdNgayKetThuc.getDate());
        if (timeBatDau.equals(timeKetThuc)) {
            System.out.println("Ngày bắt đầu bằng ngày kết thúc.");
        } else if (timeBatDau.compareTo(timeKetThuc) < 0) {
            lhd = hds.showDataHoaDonQLHoaDonFollowDateTime(timeBatDau, timeKetThuc, startRow, rowsPerPage);
            fillToTable();
        } else {
            JOptionPane.showMessageDialog(this, "Ngày bắt đầu sau ngày kết thúc.");
        }

    }//GEN-LAST:event_btnTimKiemTheoNgayActionPerformed

    private void txtNguoiTaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNguoiTaoActionPerformed
        lhd = hds.showDataHoaDonQLHoaDonFollowNguoiTao(txtNguoiTao.getText());
        jpPhanTrang.setVisible(false);
        fillToTable();
    }//GEN-LAST:event_txtNguoiTaoActionPerformed

    private void txtNguoiTaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNguoiTaoMouseClicked
        cboPhuongThucThanhToan.setSelectedIndex(3);
    }//GEN-LAST:event_txtNguoiTaoMouseClicked

    private void jdNgayBatDauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdNgayBatDauMouseClicked
        cboPhuongThucThanhToan.setSelectedIndex(3);
    }//GEN-LAST:event_jdNgayBatDauMouseClicked

    private void jdNgayKetThucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdNgayKetThucMouseClicked
        cboPhuongThucThanhToan.setSelectedIndex(3);
    }//GEN-LAST:event_jdNgayKetThucMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyHoaDon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnTimKiemTheoNgay;
    private javax.swing.JComboBox<String> cboPhuongThucThanhToan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private com.toedter.calendar.JDateChooser jdNgayBatDau;
    private com.toedter.calendar.JDateChooser jdNgayKetThuc;
    private javax.swing.JPanel jpPhanTrang;
    private javax.swing.JLabel lblPage;
    private javax.swing.JTable tblDonHang;
    private javax.swing.JTable tblHoaDonQL;
    private javax.swing.JTextField txtNguoiTao;
    // End of variables declaration//GEN-END:variables

    private void fillToTable() {
        HoaDonModel.setRowCount(0);
        for (HoaDon i : lhd) {
            DecimalFormat decimalFormat = new DecimalFormat("###,### VND");
            String formattedAmount = decimalFormat.format(i.getTongTien());
            HoaDonModel.addRow(new Object[]{i.getHoaDonId(), i.getTenPhuongThuc(), i.getNguoiTao(), formattedAmount, i.getHoTenKhachHang(), i.isTrangThai() == true ? "Đã thanh toán" : "Chưa thanh toán", i.getCreated_at()});
        }

    }

    private void fillToTableDonHang() {
        DonHangModel.setRowCount(0);

        for (DonHangSanPhamHoanChinh i : ldhsphc) {
                        DecimalFormat decimalFormat = new DecimalFormat("###,### VND");
            String formattedAmount = decimalFormat.format(i.getGiaTien());
            String thanhtien = decimalFormat.format(i.getGiaTien() * i.getSoLuong());
            
            DonHangModel.addRow(new Object[]{i.getSanPhamSanPhamChiTietId(), i.getTenSanPham(), i.getMausac(), i.getChatlieu(), i.getKichThuoc(), i.getSoLuong(), formattedAmount, thanhtien});

        }
    }

    public void computedPagination() {

        if (hds.countDataHoaDon() % rowsPerPage == 0) {
            page = hds.countDataHoaDon() / rowsPerPage;
        } else {
            page = (int) Math.ceil((double) hds.countDataHoaDon() / rowsPerPage);
        }

    }
}
