/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Service.SanPhamHoanChinhService;
import Service.SanPhamSanPhamChiTietService;
import com.itextpdf.text.DocumentException;
import java.awt.Component;
import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.SanPhamHoanChinh;

/**
 *
 * @author TB
 */
public class SanPhamAn extends javax.swing.JFrame {
    SanPhamHoanChinhService sphcsv = new SanPhamHoanChinhService();
    DefaultTableModel model = new DefaultTableModel();
    List<SanPhamHoanChinh> lsphc = new ArrayList<>();
    int index;
    SanPhamSanPhamChiTietService spspctsv = new SanPhamSanPhamChiTietService();
    /**
     * Creates new form SanPhamAn
     */
    public SanPhamAn() {
        initComponents();
        setLocationRelativeTo(null);
        model = (DefaultTableModel) tblStore.getModel();
        tblStore.setRowHeight(50);
        lsphc = sphcsv.getData();
        fillToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStore = new javax.swing.JTable();
        btnHienThiSanPham = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblStore.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Sản Phẩm", "Tên Sản Phẩm", "Loại Sản Phẩm", "Kích Thước", "Màu Sắc", "Chất Liệu", "Đơn Giá", "Số Lượng", "Hình Ảnh"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblStore);

        btnHienThiSanPham.setText("Hiển thị lại sản phẩm");
        btnHienThiSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienThiSanPhamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHienThiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHienThiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHienThiSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienThiSanPhamActionPerformed
       int indexSphc = tblStore.getSelectedRow();
       if(indexSphc == -1)
       {
           JOptionPane.showMessageDialog(this, "Bạn hãy chọn sản phẩm tương ứng");
           return;
       }
        SanPhamHoanChinh sphc = lsphc.get(indexSphc);
        int quyetdinh = JOptionPane.showConfirmDialog(this, "Bạn có muốn hiển thị sản phẩm này không ?");
        if (quyetdinh == JOptionPane.YES_OPTION) {
            boolean result = spspctsv.enableSanPhamSanPhamChiTiet(Integer.parseInt(sphc.getSanPhamId()), Integer.parseInt(sphc.getChiTietSanPhamid()));
            if (result) {
                
//                StoreForm sf = new StoreForm();
//                sf.fillToTable();
                fillToTable();
                JOptionPane.showMessageDialog(this, "đã hiển thị thành công");
            } else {
                JOptionPane.showMessageDialog(this, "đã hiển thị thất bại");
            }
        }
    }//GEN-LAST:event_btnHienThiSanPhamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SanPhamAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SanPhamAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SanPhamAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SanPhamAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SanPhamAn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHienThiSanPham;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStore;
    // End of variables declaration//GEN-END:variables

     private void fillToTable() {
        model.setRowCount(0);
        lsphc = sphcsv.getDataDisable();
        for (SanPhamHoanChinh i : lsphc) {
//            ImageIcon imic = new ImageIcon( new ImageIcon(i.getAnh()).getImage().getScaledInstance(50, 50, Image.SCALE_DEFAULT));
            model.addRow(new Object[]{i.getSanPhamId(), i.getTenSanPham(), i.getPhanLoai(), i.getKichThuoc(), i.getMauSac(), i.getChatLieu(), i.getGiaTien(), i.getSoLuong(), i.getAnh()});
            tblStore.getColumnModel().getColumn(8).setCellRenderer(new ImageRender());
            
        }
    }
    
    private class ImageRender extends DefaultTableCellRenderer {
        
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            String photoName = value.toString();
            ImageIcon imic = new ImageIcon(new ImageIcon(photoName).getImage().getScaledInstance(50, 50, Image.SCALE_DEFAULT));
            return new JLabel(imic);
        }
        
    }
}
